[package]
name = "slotmap"
version = "0.1.0"
authors = ["Orson Peters <orsonpeters@gmail.com>"]
description = "Slotmap data structure"
license = "Zlib"
homepage = "https://github.com/orlp/slotmap"
repository = "https://github.com/orlp/slotmap"
readme = "README.md"
keywords = ["slotmap", "storage", "allocator", "stable", "reference"]
categories = ["data-structures", "memory-management", "caching"]

[dependencies]
